// src/lib/emoji-data.ts

// Emoji object type: c = character, k = translation key
export type EmojiObj = { c: string; k: string };

export const categoryList = [
  "smileys_people",
  "animals_nature",
  "food_drink",
  "activity",
  "travel_places",
  "objects",
  "symbols",
  "flags",
] as const;

export type CategoryKey = (typeof categoryList)[number];

// Emoji categories with their respective emojis
export const emojiData: Record<CategoryKey, EmojiObj[]> = {
  smileys_people: [
    { c: "😀", k: "grinning_face" },
    { c: "😃", k: "grinning_face_big_eyes" },
    { c: "😄", k: "grinning_face_smiling_eyes" },
    { c: "😁", k: "beaming_face_smiling_eyes" },
    { c: "😆", k: "grinning_squinting_face" },
    { c: "😅", k: "grinning_face_sweat" },
    { c: "🤣", k: "rolling_on_floor_laughing" },
    { c: "😂", k: "face_tears_joy" },
    { c: "🙂", k: "slightly_smiling_face" },
    { c: "🙃", k: "upside_down_face" },
    { c: "😉", k: "winking_face" },
    { c: "😊", k: "smiling_face_smiling_eyes" },
    { c: "😇", k: "smiling_face_halo" },
    { c: "🥰", k: "smiling_face_hearts" },
    { c: "😍", k: "smiling_face_heart_eyes" },
    { c: "🤩", k: "star_struck" },
    { c: "😘", k: "face_blowing_kiss" },
    { c: "😗", k: "kissing_face" },
    { c: "😚", k: "kissing_face_closed_eyes" },
    { c: "😙", k: "kissing_face_smiling_eyes" },
    { c: "😋", k: "face_savoring_food" },
    { c: "😛", k: "face_tongue" },
    { c: "😜", k: "winking_face_tongue" },
    { c: "🤪", k: "zany_face" },
    { c: "😝", k: "squinting_face_tongue" },
    { c: "🤑", k: "money_mouth_face" },
    { c: "🤗", k: "hugging_face" },
    { c: "🤭", k: "face_hand_over_mouth" },
    { c: "🤫", k: "shushing_face" },
    { c: "🤔", k: "thinking_face" },
    { c: "🤐", k: "zipper_mouth_face" },
    { c: "🤨", k: "face_raised_eyebrow" },
    { c: "😐", k: "neutral_face" },
    { c: "😑", k: "expressionless_face" },
    { c: "😶", k: "face_without_mouth" },
    { c: "😏", k: "smirking_face" },
    { c: "😒", k: "unamused_face" },
    { c: "🙄", k: "face_rolling_eyes" },
    { c: "😬", k: "grimacing_face" },
    { c: "🤥", k: "lying_face" },
    { c: "😌", k: "relieved_face" },
    { c: "😔", k: "pensive_face" },
    { c: "😪", k: "sleepy_face" },
    { c: "🤤", k: "drooling_face" },
    { c: "😴", k: "sleeping_face" },
    { c: "😷", k: "face_medical_mask" },
    { c: "🤒", k: "face_thermometer" },
    { c: "🤕", k: "face_head_bandage" },
    { c: "🤢", k: "nauseated_face" },
    { c: "🤮", k: "face_vomiting" },
    { c: "🤧", k: "sneezing_face" },
    { c: "🥵", k: "hot_face" },
    { c: "🥶", k: "cold_face" },
    { c: "🥴", k: "woozy_face" },
    { c: "😵", k: "dizzy_face" },
    { c: "🤯", k: "exploding_head" },
    { c: "🤠", k: "cowboy_hat_face" },
    { c: "🥳", k: "partying_face" },
    { c: "😎", k: "smiling_face_sunglasses" },
    { c: "🤓", k: "nerd_face" },
    { c: "🧐", k: "face_monocle" },
    { c: "😕", k: "confused_face" },
    { c: "😟", k: "worried_face" },
    { c: "🙁", k: "slightly_frowning_face" },
    { c: "😮", k: "face_open_mouth" },
    { c: "😯", k: "hushed_face" },
    { c: "😲", k: "astonished_face" },
    { c: "😳", k: "flushed_face" },
    { c: "🥺", k: "pleading_face" },
    { c: "😦", k: "frowning_face_open_mouth" },
    { c: "😧", k: "anguished_face" },
    { c: "😨", k: "fearful_face" },
    { c: "😰", k: "anxious_face_sweat" },
    { c: "😥", k: "sad_relieved_face" },
    { c: "😢", k: "crying_face" },
    { c: "😭", k: "loudly_crying_face" },
    { c: "😱", k: "face_screaming_fear" },
    { c: "😖", k: "confounded_face" },
    { c: "😣", k: "persevering_face" },
    { c: "😞", k: "disappointed_face" },
    { c: "😓", k: "downcast_face_sweat" },
    { c: "😩", k: "weary_face" },
    { c: "😫", k: "tired_face" },
    { c: "🥱", k: "yawning_face" },
    { c: "😤", k: "face_steam_nose" },
    { c: "😡", k: "pouting_face" },
    { c: "😠", k: "angry_face" },
    { c: "🤬", k: "face_symbols_mouth" },
    { c: "😈", k: "smiling_face_horns" },
    { c: "👿", k: "angry_face_horns" },
    { c: "💀", k: "skull" },
    { c: "💩", k: "pile_of_poo" },
    { c: "🤡", k: "clown_face" },
    { c: "👹", k: "ogre" },
    { c: "👺", k: "goblin" },
    { c: "👻", k: "ghost" },
    { c: "👽", k: "alien" },
    { c: "👾", k: "alien_monster" },
    { c: "🤖", k: "robot" },
    { c: "😺", k: "grinning_cat" },
    { c: "😸", k: "grinning_cat_smiling_eyes" },
    { c: "😹", k: "cat_tears_joy" },
    { c: "😻", k: "smiling_cat_heart_eyes" },
    { c: "😼", k: "cat_wry_smile" },
    { c: "😽", k: "kissing_cat" },
    { c: "🙀", k: "weary_cat" },
    { c: "😿", k: "crying_cat" },
    { c: "😾", k: "pouting_cat" },
    { c: "👋", k: "waving_hand" },
    { c: "🤚", k: "raised_back_hand" },
    { c: "🖐", k: "hand_fingers_splayed" },
    { c: "✋", k: "raised_hand" },
    { c: "🖖", k: "vulcan_salute" },
    { c: "👌", k: "ok_hand" },
    { c: "🤏", k: "pinching_hand" },
    { c: "✌", k: "victory_hand" },
    { c: "🤞", k: "crossed_fingers" },
    { c: "🤟", k: "love_you_gesture" },
    { c: "🤘", k: "sign_horns" },
    { c: "🤙", k: "call_me_hand" },
    { c: "👈", k: "backhand_index_left" },
    { c: "👉", k: "backhand_index_right" },
    { c: "👆", k: "backhand_index_up" },
    { c: "🖕", k: "middle_finger" },
    { c: "👇", k: "backhand_index_down" },
    { c: "☝", k: "index_pointing_up" },
    { c: "👍", k: "thumbs_up" },
    { c: "👎", k: "thumbs_down" },
    { c: "✊", k: "raised_fist" },
    { c: "👊", k: "oncoming_fist" },
    { c: "🤛", k: "left_facing_fist" },
    { c: "🤜", k: "right_facing_fist" },
    { c: "👏", k: "clapping_hands" },
    { c: "🙌", k: "raising_hands" },
    { c: "👐", k: "open_hands" },
    { c: "🤲", k: "palms_up_together" },
    { c: "🤝", k: "handshake" },
    { c: "🙏", k: "folded_hands" },
    { c: "✍", k: "writing_hand" },
    { c: "💅", k: "nail_polish" },
    { c: "🤳", k: "selfie" },
    { c: "💪", k: "flexed_biceps" },
    { c: "🦾", k: "mechanical_arm" },
    { c: "🦿", k: "mechanical_leg" },
    { c: "🦵", k: "leg" },
    { c: "🦶", k: "foot" },
    { c: "👂", k: "ear" },
    { c: "🦻", k: "ear_hearing_aid" },
    { c: "👃", k: "nose" },
    { c: "🧠", k: "brain" },
    { c: "🦷", k: "tooth" },
    { c: "🦴", k: "bone" },
    { c: "👀", k: "eyes" },
    { c: "👁️", k: "eye" },
    { c: "👅", k: "tongue" },
    { c: "👄", k: "mouth" },
  ],
  animals_nature: [
    { c: "🐶", k: "dog_face" },
    { c: "🐱", k: "cat_face" },
    { c: "🐭", k: "mouse_face" },
    { c: "🐹", k: "hamster_face" },
    { c: "🐰", k: "rabbit_face" },
    { c: "🦊", k: "fox" },
    { c: "🐻", k: "bear" },
    { c: "🐼", k: "panda" },
    { c: "🐨", k: "koala" },
    { c: "🐯", k: "tiger_face" },
    { c: "🦁", k: "lion" },
    { c: "🐮", k: "cow_face" },
    { c: "🐷", k: "pig_face" },
    { c: "🐽", k: "pig_nose" },
    { c: "🐸", k: "frog" },
    { c: "🐵", k: "monkey_face" },
    { c: "🙈", k: "see_no_evil_monkey" },
    { c: "🙉", k: "hear_no_evil_monkey" },
    { c: "🙊", k: "speak_no_evil_monkey" },
    { c: "🐒", k: "monkey" },
    { c: "🐔", k: "chicken" },
    { c: "🐧", k: "penguin" },
    { c: "🐦", k: "bird" },
    { c: "🐤", k: "baby_chick" },
    { c: "🐣", k: "hatching_chick" },
    { c: "🐥", k: "front_facing_baby_chick" },
    { c: "🦆", k: "duck" },
    { c: "🦅", k: "eagle" },
    { c: "🦉", k: "owl" },
    { c: "🦇", k: "bat" },
    { c: "🐺", k: "wolf" },
    { c: "🐗", k: "boar" },
    { c: "🐴", k: "horse_face" },
    { c: "🦄", k: "unicorn" },
    { c: "🐝", k: "honeybee" },
    { c: "🐛", k: "bug" },
    { c: "🦋", k: "butterfly" },
    { c: "🐌", k: "snail" },
    { c: "🐞", k: "lady_beetle" },
    { c: "🐜", k: "ant" },
    { c: "🦟", k: "mosquito" },
    { c: "🦗", k: "cricket" },
    { c: "🕷️", k: "spider" },
    { c: "🕸️", k: "spider_web" },
    { c: "🦂", k: "scorpion" },
    { c: "🐢", k: "turtle" },
    { c: "🐍", k: "snake" },
    { c: "🦎", k: "lizard" },
    { c: "🦖", k: "t_rex" },
    { c: "🦕", k: "sauropod" },
    { c: "🐙", k: "octopus" },
    { c: "🦑", k: "squid" },
    { c: "🦐", k: "shrimp" },
    { c: "🦞", k: "lobster" },
    { c: "🦀", k: "crab" },
    { c: "🐡", k: "blowfish" },
    { c: "🐠", k: "tropical_fish" },
    { c: "🐟", k: "fish" },
    { c: "🐬", k: "dolphin" },
    { c: "🐳", k: "spouting_whale" },
    { c: "🐋", k: "whale" },
    { c: "🦈", k: "shark" },
    { c: "🐊", k: "crocodile" },
    { c: "🐅", k: "tiger" },
    { c: "🐆", k: "leopard" },
    { c: "🦓", k: "zebra" },
    { c: "🦍", k: "gorilla" },
    { c: "🦧", k: "orangutan" },
    { c: "🐘", k: "elephant" },
    { c: "🦛", k: "hippopotamus" },
    { c: "🦏", k: "rhinoceros" },
    { c: "🐪", k: "camel" },
    { c: "🐫", k: "two_hump_camel" },
    { c: "🦒", k: "giraffe" },
    { c: "🦘", k: "kangaroo" },
    { c: "🐃", k: "water_buffalo" },
    { c: "🐂", k: "ox" },
    { c: "🐄", k: "cow" },
    { c: "🐎", k: "horse" },
    { c: "🐖", k: "pig" },
    { c: "🐏", k: "ram" },
    { c: "🐑", k: "ewe" },
    { c: "🦙", k: "llama" },
    { c: "🐐", k: "goat" },
    { c: "🦌", k: "deer" },
    { c: "🐕", k: "dog" },
    { c: "🐩", k: "poodle" },
    { c: "🦮", k: "guide_dog" },
    { c: "🐕‍🦺", k: "service_dog" },
    { c: "🐈", k: "cat" },
    { c: "🐓", k: "rooster" },
    { c: "🦃", k: "turkey" },
    { c: "🦚", k: "peacock" },
    { c: "🦜", k: "parrot" },
    { c: "🦢", k: "swan" },
    { c: "🦩", k: "flamingo" },
    { c: "🕊️", k: "dove" },
    { c: "🐇", k: "rabbit" },
    { c: "🦝", k: "raccoon" },
    { c: "🦨", k: "skunk" },
    { c: "🦡", k: "badger" },
    { c: "🦦", k: "otter" },
    { c: "🦥", k: "sloth" },
    { c: "🐁", k: "mouse" },
    { c: "🐀", k: "rat" },
    { c: "🐿️", k: "chipmunk" },
    { c: "🦔", k: "hedgehog" },
    { c: "🌲", k: "evergreen_tree" },
    { c: "🌳", k: "deciduous_tree" },
    { c: "🌴", k: "palm_tree" },
    { c: "🌱", k: "seedling" },
    { c: "🌿", k: "herb" },
    { c: "☘️", k: "shamrock" },
    { c: "🍀", k: "four_leaf_clover" },
    { c: "🎍", k: "pine_decoration" },
    { c: "🎋", k: "tanabata_tree" },
    { c: "🍃", k: "leaf_fluttering_wind" },
    { c: "🍂", k: "fallen_leaf" },
    { c: "🍁", k: "maple_leaf" },
    { c: "🍄", k: "mushroom" },
    { c: "🌾", k: "sheaf_rice" },
    { c: "💐", k: "bouquet" },
    { c: "🌷", k: "tulip" },
    { c: "🌹", k: "rose" },
    { c: "🥀", k: "wilted_flower" },
    { c: "🌺", k: "hibiscus" },
    { c: "🌸", k: "cherry_blossom" },
    { c: "🌼", k: "blossom" },
    { c: "🌻", k: "sunflower" },
    { c: "🌞", k: "sun_with_face" },
    { c: "🌝", k: "full_moon_face" },
    { c: "🌛", k: "first_quarter_moon_face" },
    { c: "🌜", k: "last_quarter_moon_face" },
    { c: "🌚", k: "new_moon_face" },
    { c: "🌕", k: "full_moon" },
    { c: "🌖", k: "waning_gibbous_moon" },
    { c: "🌗", k: "last_quarter_moon" },
    { c: "🌘", k: "waning_crescent_moon" },
    { c: "🌑", k: "new_moon" },
    { c: "🌒", k: "waxing_crescent_moon" },
    { c: "🌓", k: "first_quarter_moon" },
    { c: "🌔", k: "waxing_gibbous_moon" },
    { c: "🌙", k: "crescent_moon" },
    { c: "🌎", k: "globe_americas" },
    { c: "🌍", k: "globe_europe_africa" },
    { c: "🌏", k: "globe_asia_australia" },
    { c: "💫", k: "dizzy" },
    { c: "⭐", k: "star" },
    { c: "🌟", k: "glowing_star" },
    { c: "✨", k: "sparkles" },
    { c: "⚡", k: "high_voltage" },
    { c: "☄️", k: "comet" },
    { c: "💥", k: "collision" },
    { c: "🔥", k: "fire" },
    { c: "🌪️", k: "tornado" },
    { c: "🌈", k: "rainbow" },
  ],
  food_drink: [
    { c: "🍇", k: "grapes" },
    { c: "🍈", k: "melon" },
    { c: "🍉", k: "watermelon" },
    { c: "🍊", k: "tangerine" },
    { c: "🍋", k: "lemon" },
    { c: "🍌", k: "banana" },
    { c: "🍍", k: "pineapple" },
    { c: "🥭", k: "mango" },
    { c: "🍎", k: "red_apple" },
    { c: "🍏", k: "green_apple" },
    { c: "🍐", k: "pear" },
    { c: "🍑", k: "peach" },
    { c: "🍒", k: "cherries" },
    { c: "🍓", k: "strawberry" },
    { c: "🥝", k: "kiwi_fruit" },
    { c: "🍅", k: "tomato" },
    { c: "🥥", k: "coconut" },
    { c: "🥑", k: "avocado" },
    { c: "🍆", k: "eggplant" },
    { c: "🥔", k: "potato" },
    { c: "🥕", k: "carrot" },
    { c: "🌽", k: "ear_corn" },
    { c: "🌶", k: "hot_pepper" },
    { c: "🥒", k: "cucumber" },
    { c: "🥬", k: "leafy_green" },
    { c: "🥦", k: "broccoli" },
    { c: "🧄", k: "garlic" },
    { c: "🧅", k: "onion" },
    { c: "🍄", k: "mushroom" },
    { c: "🥜", k: "peanuts" },
    { c: "🌰", k: "chestnut" },
    { c: "🍞", k: "bread" },
    { c: "🥐", k: "croissant" },
    { c: "🥖", k: "baguette_bread" },
    { c: "🥨", k: "pretzel" },
    { c: "🥯", k: "bagel" },
    { c: "🥞", k: "pancakes" },
    { c: "🧇", k: "waffle" },
    { c: "🧀", k: "cheese_wedge" },
    { c: "🍖", k: "meat_bone" },
    { c: "🍗", k: "poultry_leg" },
    { c: "🥩", k: "cut_meat" },
    { c: "🥓", k: "bacon" },
    { c: "🍔", k: "hamburger" },
    { c: "🍟", k: "french_fries" },
    { c: "🍕", k: "pizza" },
    { c: "🌭", k: "hot_dog" },
    { c: "🥪", k: "sandwich" },
    { c: "🌮", k: "taco" },
    { c: "🌯", k: "burrito" },
    { c: "🥙", k: "stuffed_flatbread" },
    { c: "🧆", k: "falafel" },
    { c: "🥚", k: "egg" },
    { c: "🍳", k: "cooking" },
    { c: "🥘", k: "shallow_pan_food" },
    { c: "🍲", k: "pot_food" },
    { c: "🥣", k: "bowl_spoon" },
    { c: "🥗", k: "green_salad" },
    { c: "🍿", k: "popcorn" },
    { c: "🧈", k: "butter" },
    { c: "🧂", k: "salt" },
    { c: "🥫", k: "canned_food" },
    { c: "🍱", k: "bento_box" },
    { c: "🍘", k: "rice_cracker" },
    { c: "🍙", k: "rice_ball" },
    { c: "🍚", k: "cooked_rice" },
    { c: "🍛", k: "curry_rice" },
    { c: "🍜", k: "steaming_bowl" },
    { c: "🍝", k: "spaghetti" },
    { c: "🍠", k: "roasted_sweet_potato" },
    { c: "🍢", k: "oden" },
    { c: "🍣", k: "sushi" },
    { c: "🍤", k: "fried_shrimp" },
    { c: "🍥", k: "fish_cake_swirl" },
    { c: "🥮", k: "moon_cake" },
    { c: "🍡", k: "dango" },
    { c: "🥟", k: "dumpling" },
    { c: "🥠", k: "fortune_cookie" },
    { c: "🥡", k: "takeout_box" },
    { c: "🦀", k: "crab" },
    { c: "🦞", k: "lobster" },
    { c: "🦐", k: "shrimp" },
    { c: "🦑", k: "squid" },
    { c: "🦪", k: "oyster" },
    { c: "🍦", k: "soft_ice_cream" },
    { c: "🍧", k: "shaved_ice" },
    { c: "🍨", k: "ice_cream" },
    { c: "🍩", k: "doughnut" },
    { c: "🍪", k: "cookie" },
    { c: "🎂", k: "birthday_cake" },
    { c: "🍰", k: "shortcake" },
    { c: "🧁", k: "cupcake" },
    { c: "🥧", k: "pie" },
    { c: "🍫", k: "chocolate_bar" },
    { c: "🍬", k: "candy" },
    { c: "🍭", k: "lollipop" },
    { c: "🍮", k: "custard" },
    { c: "🍯", k: "honey_pot" },
    { c: "🍼", k: "baby_bottle" },
    { c: "🥛", k: "glass_milk" },
    { c: "☕", k: "hot_beverage" },
    { c: "🍵", k: "teacup_without_handle" },
    { c: "🍶", k: "sake" },
    { c: "🍾", k: "bottle_popping_cork" },
    { c: "🍷", k: "wine_glass" },
    { c: "🍸", k: "cocktail_glass" },
    { c: "🍹", k: "tropical_drink" },
    { c: "🍺", k: "beer_mug" },
    { c: "🍻", k: "clinking_beer_mugs" },
    { c: "🥂", k: "clinking_glasses" },
    { c: "🥃", k: "tumbler_glass" },
    { c: "🥤", k: "cup_straw" },
    { c: "🧃", k: "beverage_box" },
    { c: "🧉", k: "mate" },
    { c: "🧊", k: "ice" },
  ],
  activity: [
    { c: "⚽", k: "soccer_ball" },
    { c: "🏀", k: "basketball" },
    { c: "🏈", k: "american_football" },
    { c: "⚾", k: "baseball" },
    { c: "🥎", k: "softball" },
    { c: "🎾", k: "tennis" },
    { c: "🏐", k: "volleyball" },
    { c: "🏉", k: "rugby_football" },
    { c: "🥏", k: "flying_disc" },
    { c: "🎱", k: "pool_8_ball" },
    { c: "🪀", k: "yo_yo" },
    { c: "🏓", k: "ping_pong" },
    { c: "🏸", k: "badminton" },
    { c: "🏒", k: "ice_hockey" },
    { c: "🏑", k: "field_hockey" },
    { c: "🥍", k: "lacrosse" },
    { c: "🏏", k: "cricket_game" },
    { c: "🥅", k: "goal_net" },
    { c: "⛳", k: "flag_hole" },
    { c: "🪁", k: "kite" },
    { c: "🏹", k: "bow_arrow" },
    { c: "🎣", k: "fishing_pole" },
    { c: "🤿", k: "diving_mask" },
    { c: "🥊", k: "boxing_glove" },
    { c: "🥋", k: "martial_arts_uniform" },
    { c: "🎽", k: "running_shirt" },
    { c: "🛹", k: "skateboard" },
    { c: "🛷", k: "sled" },
    { c: "⛸️", k: "ice_skate" },
    { c: "🥌", k: "curling_stone" },
    { c: "🎿", k: "skis" },
    { c: "⛷️", k: "skier" },
    { c: "🏂", k: "snowboarder" },
    { c: "🪂", k: "parachute" },
    { c: "🏋️", k: "person_lifting_weights" },
    { c: "🤼", k: "people_wrestling" },
    { c: "🤸", k: "person_cartwheeling" },
    { c: "🤺", k: "person_fencing" },
    { c: "⛹️", k: "person_bouncing_ball" },
    { c: "🤾", k: "person_playing_handball" },
    { c: "🏌️", k: "person_golfing" },
    { c: "🏇", k: "horse_racing" },
    { c: "🧘", k: "person_lotus_position" },
    { c: "🏊", k: "person_swimming" },
    { c: "🤽", k: "person_playing_water_polo" },
    { c: "🚣", k: "person_rowing_boat" },
    { c: "🧗", k: "person_climbing" },
    { c: "🚵", k: "person_mountain_biking" },
    { c: "🚴", k: "person_biking" },
    { c: "🏆", k: "trophy" },
    { c: "🥇", k: "1st_place_medal" },
    { c: "🥈", k: "2nd_place_medal" },
    { c: "🥉", k: "3rd_place_medal" },
    { c: "🏅", k: "sports_medal" },
    { c: "🎖️", k: "military_medal" },
    { c: "🏵️", k: "rosette" },
    { c: "🎗️", k: "reminder_ribbon" },
    { c: "🎫", k: "ticket" },
    { c: "🎟️", k: "admission_tickets" },
    { c: "🎪", k: "circus_tent" },
    { c: "🤹", k: "person_juggling" },
    { c: "🎭", k: "performing_arts" },
    { c: "🩰", k: "ballet_shoes" },
    { c: "🎨", k: "artist_palette" },
    { c: "🎬", k: "clapper_board" },
    { c: "🎤", k: "microphone" },
    { c: "🎧", k: "headphone" },
    { c: "🎼", k: "musical_score" },
    { c: "🎹", k: "musical_keyboard" },
    { c: "🥁", k: "drum" },
    { c: "🎷", k: "saxophone" },
    { c: "🎺", k: "trumpet" },
    { c: "🎸", k: "guitar" },
    { c: "🪕", k: "banjo" },
    { c: "🎻", k: "violin" },
    { c: "🎲", k: "game_die" },
    { c: "♟️", k: "chess_pawn" },
    { c: "🎯", k: "bullseye" },
    { c: "🎳", k: "bowling" },
    { c: "🎮", k: "video_game" },
    { c: "🎰", k: "slot_machine" },
    { c: "🧩", k: "puzzle_piece" },
  ],
  travel_places: [
    { c: "🚗", k: "automobile" },
    { c: "🚕", k: "taxi" },
    { c: "🚙", k: "sport_utility_vehicle" },
    { c: "🚌", k: "bus" },
    { c: "🚎", k: "trolleybus" },
    { c: "🏎️", k: "racing_car" },
    { c: "🚓", k: "police_car" },
    { c: "🚑", k: "ambulance" },
    { c: "🚒", k: "fire_engine" },
    { c: "🚐", k: "minibus" },
    { c: "🚚", k: "delivery_truck" },
    { c: "🚛", k: "articulated_lorry" },
    { c: "🚜", k: "tractor" },
    { c: "🦯", k: "white_cane" },
    { c: "🦽", k: "manual_wheelchair" },
    { c: "🦼", k: "motorized_wheelchair" },
    { c: "🛴", k: "kick_scooter" },
    { c: "🚲", k: "bicycle" },
    { c: "🛵", k: "motor_scooter" },
    { c: "🏍️", k: "motorcycle" },
    { c: "🛺", k: "auto_rickshaw" },
    { c: "🚨", k: "police_car_light" },
    { c: "🚔", k: "oncoming_police_car" },
    { c: "🚍", k: "oncoming_bus" },
    { c: "🚘", k: "oncoming_automobile" },
    { c: "🚖", k: "oncoming_taxi" },
    { c: "🚡", k: "aerial_tramway" },
    { c: "🚠", k: "mountain_cableway" },
    { c: "🚟", k: "suspension_railway" },
    { c: "🚃", k: "railway_car" },
    { c: "🚋", k: "tram_car" },
    { c: "🚞", k: "mountain_railway" },
    { c: "🚝", k: "monorail" },
    { c: "🚄", k: "high_speed_train" },
    { c: "🚅", k: "bullet_train" },
    { c: "🚈", k: "light_rail" },
    { c: "🚂", k: "locomotive" },
    { c: "🚆", k: "train" },
    { c: "🚇", k: "metro" },
    { c: "🚊", k: "tram" },
    { c: "🚉", k: "station" },
    { c: "✈️", k: "airplane" },
    { c: "🛫", k: "airplane_departure" },
    { c: "🛬", k: "airplane_arrival" },
    { c: "🛩️", k: "small_airplane" },
    { c: "💺", k: "seat" },
    { c: "🛰️", k: "satellite" },
    { c: "🚀", k: "rocket" },
    { c: "🛸", k: "flying_saucer" },
    { c: "🚁", k: "helicopter" },
    { c: "🛶", k: "canoe" },
    { c: "⛵", k: "sailboat" },
    { c: "🚤", k: "speedboat" },
    { c: "🛥️", k: "motor_boat" },
    { c: "🛳️", k: "passenger_ship" },
    { c: "⛴️", k: "ferry" },
    { c: "🚢", k: "ship" },
    { c: "⚓", k: "anchor" },
    { c: "⛽", k: "fuel_pump" },
    { c: "🚧", k: "construction" },
    { c: "🚦", k: "vertical_traffic_light" },
    { c: "🚥", k: "horizontal_traffic_light" },
    { c: "🚏", k: "bus_stop" },
    { c: "🗺️", k: "world_map" },
    { c: "🗿", k: "moai" },
    { c: "🗽", k: "statue_liberty" },
    { c: "🗼", k: "tokyo_tower" },
    { c: "🏰", k: "castle" },
    { c: "🏯", k: "japanese_castle" },
    { c: "🏟️", k: "stadium" },
    { c: "🎡", k: "ferris_wheel" },
    { c: "🎢", k: "roller_coaster" },
    { c: "🎠", k: "carousel_horse" },
    { c: "⛲", k: "fountain" },
    { c: "⛱️", k: "umbrella_ground" },
    { c: "🏖️", k: "beach_umbrella" },
    { c: "🏝️", k: "desert_island" },
    { c: "🏜️", k: "desert" },
    { c: "🌋", k: "volcano" },
    { c: "⛰️", k: "mountain" },
    { c: "🏔️", k: "snow_capped_mountain" },
    { c: "🗻", k: "mount_fuji" },
    { c: "🏕️", k: "camping" },
    { c: "⛺", k: "tent" },
    { c: "🏠", k: "house" },
    { c: "🏡", k: "house_garden" },
    { c: "🏘️", k: "houses" },
    { c: "🏚️", k: "derelict_house" },
    { c: "🏗️", k: "building_construction" },
    { c: "🏭", k: "factory" },
    { c: "🏢", k: "office_building" },
    { c: "🏬", k: "department_store" },
    { c: "🏣", k: "japanese_post_office" },
    { c: "🏤", k: "post_office" },
    { c: "🏥", k: "hospital" },
    { c: "🏦", k: "bank" },
    { c: "🏨", k: "hotel" },
    { c: "🏪", k: "convenience_store" },
    { c: "🏫", k: "school" },
    { c: "🏩", k: "love_hotel" },
    { c: "💒", k: "wedding" },
    { c: "🏛️", k: "classical_building" },
    { c: "⛪", k: "church" },
    { c: "🕌", k: "mosque" },
    { c: "🕍", k: "synagogue" },
    { c: "🛕", k: "hindu_temple" },
    { c: "🕋", k: "kaaba" },
    { c: "⛩️", k: "shinto_shrine" },
    { c: "🛤️", k: "railway_track" },
    { c: "🛣️", k: "motorway" },
    { c: "🗾", k: "map_japan" },
    { c: "🎑", k: "moon_viewing_ceremony" },
    { c: "🏞️", k: "national_park" },
    { c: "🌅", k: "sunrise" },
    { c: "🌄", k: "sunrise_mountains" },
    { c: "🌠", k: "shooting_star" },
    { c: "🎇", k: "sparkler" },
    { c: "🎆", k: "fireworks" },
    { c: "🌇", k: "sunset" },
    { c: "🌆", k: "cityscape_dusk" },
    { c: "🏙️", k: "cityscape" },
    { c: "🌃", k: "night_stars" },
    { c: "🌌", k: "milky_way" },
    { c: "🌉", k: "bridge_night" },
    { c: "🌁", k: "foggy" },
  ],
  objects: [
    { c: "⌚", k: "watch" },
    { c: "📱", k: "mobile_phone" },
    { c: "📲", k: "mobile_phone_arrow" },
    { c: "💻", k: "laptop" },
    { c: "⌨️", k: "keyboard" },
    { c: "🖥️", k: "desktop_computer" },
    { c: "🖨️", k: "printer" },
    { c: "🖱️", k: "computer_mouse" },
    { c: "🖲️", k: "trackball" },
    { c: "🕹️", k: "joystick" },
    { c: "🗜️", k: "clamp" },
    { c: "💽", k: "computer_disk" },
    { c: "💾", k: "floppy_disk" },
    { c: "💿", k: "optical_disk" },
    { c: "📀", k: "dvd" },
    { c: "📼", k: "videocassette" },
    { c: "📷", k: "camera" },
    { c: "📸", k: "camera_flash" },
    { c: "📹", k: "video_camera" },
    { c: "🎥", k: "movie_camera" },
    { c: "📽️", k: "film_projector" },
    { c: "🎞️", k: "film_frames" },
    { c: "📞", k: "telephone_receiver" },
    { c: "☎️", k: "telephone" },
    { c: "📟", k: "pager" },
    { c: "📠", k: "fax_machine" },
    { c: "📺", k: "television" },
    { c: "📻", k: "radio" },
    { c: "🎙️", k: "studio_microphone" },
    { c: "🎚️", k: "level_slider" },
    { c: "🎛️", k: "control_knobs" },
    { c: "🧭", k: "compass" },
    { c: "⏱️", k: "stopwatch" },
    { c: "⏲️", k: "timer_clock" },
    { c: "⏰", k: "alarm_clock" },
    { c: "🕰️", k: "mantelpiece_clock" },
    { c: "⌛", k: "hourglass_done" },
    { c: "⏳", k: "hourglass_not_done" },
    { c: "📡", k: "satellite_antenna" },
    { c: "🔋", k: "battery" },
    { c: "🔌", k: "electric_plug" },
    { c: "💡", k: "light_bulb" },
    { c: "🔦", k: "flashlight" },
    { c: "🕯️", k: "candle" },
    { c: "🪔", k: "diya_lamp" },
    { c: "🧯", k: "fire_extinguisher" },
    { c: "🛢️", k: "oil_drum" },
    { c: "💸", k: "money_wings" },
    { c: "💵", k: "dollar_banknote" },
    { c: "💴", k: "yen_banknote" },
    { c: "💶", k: "euro_banknote" },
    { c: "💷", k: "pound_banknote" },
    { c: "💰", k: "money_bag" },
    { c: "💳", k: "credit_card" },
    { c: "💎", k: "gem_stone" },
    { c: "⚖️", k: "balance_scale" },
    { c: "🧰", k: "toolbox" },
    { c: "🔧", k: "wrench" },
    { c: "🔨", k: "hammer" },
    { c: "⚒️", k: "hammer_pick" },
    { c: "🛠️", k: "hammer_wrench" },
    { c: "⛏️", k: "pick" },
    { c: "🔩", k: "nut_bolt" },
    { c: "⚙️", k: "gear" },
    { c: "🧱", k: "brick" },
    { c: "⛓️", k: "chains" },
    { c: "🧲", k: "magnet" },
    { c: "🔫", k: "water_pistol" },
    { c: "💣", k: "bomb" },
    { c: "🧨", k: "firecracker" },
    { c: "🪓", k: "axe" },
    { c: "🔪", k: "kitchen_knife" },
    { c: "🗡️", k: "dagger" },
    { c: "⚔️", k: "crossed_swords" },
    { c: "🛡️", k: "shield" },
    { c: "🚬", k: "cigarette" },
    { c: "⚰️", k: "coffin" },
    { c: "⚱️", k: "funeral_urn" },
    { c: "🏺", k: "amphora" },
    { c: "🔮", k: "crystal_ball" },
    { c: "📿", k: "prayer_beads" },
    { c: "🧿", k: "nazar_amulet" },
    { c: "💈", k: "barber_pole" },
    { c: "⚗️", k: "alembic" },
    { c: "🔭", k: "telescope" },
    { c: "🔬", k: "microscope" },
    { c: "🕳️", k: "hole" },
    { c: "🩹", k: "adhesive_bandage" },
    { c: "🩺", k: "stethoscope" },
    { c: "💊", k: "pill" },
    { c: "💉", k: "syringe" },
    { c: "🩸", k: "drop_blood" },
    { c: "🧬", k: "dna" },
    { c: "🦠", k: "microbe" },
    { c: "🧫", k: "petri_dish" },
    { c: "🧪", k: "test_tube" },
    { c: "🌡️", k: "thermometer" },
    { c: "🧹", k: "broom" },
    { c: "🧺", k: "basket" },
    { c: "🧻", k: "roll_paper" },
    { c: "🚽", k: "toilet" },
    { c: "🚰", k: "potable_water" },
    { c: "🚿", k: "shower" },
    { c: "🛁", k: "bathtub" },
    { c: "🛀", k: "person_taking_bath" },
    { c: "🧼", k: "soap" },
    { c: "🪒", k: "razor" },
    { c: "🧽", k: "sponge" },
    { c: "🧴", k: "lotion_bottle" },
    { c: "🛎️", k: "bellhop_bell" },
    { c: "🔑", k: "key" },
    { c: "🗝️", k: "old_key" },
    { c: "🚪", k: "door" },
    { c: "🪑", k: "chair" },
    { c: "🛋️", k: "couch_lamp" },
    { c: "🛏️", k: "bed" },
    { c: "🛌", k: "person_bed" },
    { c: "🧸", k: "teddy_bear" },
    { c: "🖼️", k: "framed_picture" },
    { c: "🛍️", k: "shopping_bags" },
    { c: "🛒", k: "shopping_cart" },
    { c: "🎁", k: "wrapped_gift" },
    { c: "🎈", k: "balloon" },
    { c: "🎏", k: "carp_streamer" },
    { c: "🎀", k: "ribbon" },
    { c: "🎊", k: "confetti_ball" },
    { c: "🎉", k: "party_popper" },
    { c: "🎎", k: "japanese_dolls" },
    { c: "🏮", k: "red_paper_lantern" },
    { c: "🎐", k: "wind_chime" },
    { c: "🧧", k: "red_envelope" },
    { c: "✉️", k: "envelope" },
    { c: "📩", k: "envelope_arrow" },
    { c: "📨", k: "incoming_envelope" },
    { c: "📧", k: "e_mail" },
    { c: "💌", k: "love_letter" },
    { c: "📥", k: "inbox_tray" },
    { c: "📤", k: "outbox_tray" },
    { c: "📦", k: "package" },
    { c: "🏷️", k: "label" },
    { c: "📪", k: "closed_mailbox_lowered_flag" },
    { c: "📫", k: "closed_mailbox_raised_flag" },
    { c: "📬", k: "open_mailbox_raised_flag" },
    { c: "📭", k: "open_mailbox_lowered_flag" },
    { c: "📮", k: "postbox" },
    { c: "📯", k: "postal_horn" },
    { c: "📜", k: "scroll" },
    { c: "📃", k: "page_curl" },
    { c: "📄", k: "page_facing_up" },
    { c: "📑", k: "bookmark_tabs" },
    { c: "🧾", k: "receipt" },
    { c: "📊", k: "bar_chart" },
    { c: "📈", k: "chart_increasing" },
    { c: "📉", k: "chart_decreasing" },
    { c: "🗒️", k: "spiral_notepad" },
    { c: "🗓️", k: "spiral_calendar" },
    { c: "📆", k: "tear_off_calendar" },
    { c: "📅", k: "calendar" },
    { c: "🗑️", k: "wastebasket" },
    { c: "📇", k: "card_index" },
    { c: "🗃️", k: "card_file_box" },
    { c: "🗳️", k: "ballot_box_ballot" },
    { c: "🗄️", k: "file_cabinet" },
    { c: "📋", k: "clipboard" },
    { c: "📁", k: "file_folder" },
    { c: "📂", k: "open_file_folder" },
    { c: "🗂️", k: "card_index_dividers" },
    { c: "🗞️", k: "rolled_up_newspaper" },
    { c: "📰", k: "newspaper" },
    { c: "📓", k: "notebook" },
    { c: "📔", k: "notebook_decorative_cover" },
    { c: "📒", k: "ledger" },
    { c: "📕", k: "closed_book" },
    { c: "📗", k: "green_book" },
    { c: "📘", k: "blue_book" },
    { c: "📙", k: "orange_book" },
    { c: "📚", k: "books" },
    { c: "📖", k: "open_book" },
    { c: "🔖", k: "bookmark" },
    { c: "🧷", k: "safety_pin" },
    { c: "🔗", k: "link" },
    { c: "📎", k: "paperclip" },
    { c: "🖇️", k: "linked_paperclips" },
    { c: "📐", k: "triangular_ruler" },
    { c: "📏", k: "straight_ruler" },
    { c: "🧮", k: "abacus" },
    { c: "📌", k: "pushpin" },
    { c: "📍", k: "round_pushpin" },
    { c: "✂️", k: "scissors" },
    { c: "🖊️", k: "pen" },
    { c: "🖋️", k: "fountain_pen" },
    { c: "✒️", k: "black_nib" },
    { c: "🖌️", k: "paintbrush" },
    { c: "🖍️", k: "crayon" },
    { c: "📝", k: "memo" },
  ],
  symbols: [
    { c: "❤️", k: "red_heart" },
    { c: "🧡", k: "orange_heart" },
    { c: "💛", k: "yellow_heart" },
    { c: "💚", k: "green_heart" },
    { c: "💙", k: "blue_heart" },
    { c: "💜", k: "purple_heart" },
    { c: "🖤", k: "black_heart" },
    { c: "🤍", k: "white_heart" },
    { c: "🤎", k: "brown_heart" },
    { c: "💔", k: "broken_heart" },
    { c: "❣️", k: "heart_exclamation" },
    { c: "💕", k: "two_hearts" },
    { c: "💞", k: "revolving_hearts" },
    { c: "💓", k: "beating_heart" },
    { c: "💗", k: "growing_heart" },
    { c: "💖", k: "sparkling_heart" },
    { c: "💘", k: "heart_arrow" },
    { c: "💝", k: "heart_ribbon" },
    { c: "💟", k: "heart_decoration" },
    { c: "☮️", k: "peace_symbol" },
    { c: "✝️", k: "latin_cross" },
    { c: "☪️", k: "star_crescent" },
    { c: "🕉️", k: "om" },
    { c: "☸️", k: "wheel_dharma" },
    { c: "✡️", k: "star_david" },
    { c: "🔯", k: "dotted_six_pointed_star" },
    { c: "🕎", k: "menorah" },
    { c: "☯️", k: "yin_yang" },
    { c: "☦️", k: "orthodox_cross" },
    { c: "🛐", k: "place_worship" },
    { c: "⛎", k: "ophiuchus" },
    { c: "♈", k: "aries" },
    { c: "♉", k: "taurus" },
    { c: "♊", k: "gemini" },
    { c: "♋", k: "cancer" },
    { c: "♌", k: "leo" },
    { c: "♍", k: "virgo" },
    { c: "♎", k: "libra" },
    { c: "♏", k: "scorpio" },
    { c: "♐", k: "sagittarius" },
    { c: "♑", k: "capricorn" },
    { c: "♒", k: "aquarius" },
    { c: "♓", k: "pisces" },
    { c: "🆔", k: "id_button" },
    { c: "⚛️", k: "atom_symbol" },
    { c: "🉑", k: "japanese_acceptable_button" },
    { c: "☢️", k: "radioactive" },
    { c: "☣️", k: "biohazard" },
    { c: "📴", k: "mobile_phone_off" },
    { c: "📳", k: "vibration_mode" },
    { c: "🈶", k: "japanese_not_free_charge_button" },
    { c: "🈚", k: "japanese_free_charge_button" },
    { c: "🈸", k: "japanese_application_button" },
    { c: "🈺", k: "japanese_open_business_button" },
    { c: "🈷️", k: "japanese_monthly_amount_button" },
    { c: "✴️", k: "eight_pointed_star" },
    { c: "🆚", k: "vs_button" },
    { c: "💮", k: "white_flower" },
    { c: "🉐", k: "japanese_bargain_button" },
    { c: "㊙️", k: "japanese_secret_button" },
    { c: "㊗️", k: "japanese_congratulations_button" },
    { c: "🈴", k: "japanese_passing_grade_button" },
    { c: "🈵", k: "japanese_no_vacancy_button" },
    { c: "🈹", k: "japanese_discount_button" },
    { c: "🈲", k: "japanese_prohibited_button" },
    { c: "🅰️", k: "a_button_blood_type" },
    { c: "🅱️", k: "b_button_blood_type" },
    { c: "🆎", k: "ab_button_blood_type" },
    { c: "🆑", k: "cl_button" },
    { c: "🅾️", k: "o_button_blood_type" },
    { c: "🆘", k: "sos_button" },
    { c: "❌", k: "cross_mark" },
    { c: "⭕", k: "hollow_red_circle" },
    { c: "🛑", k: "stop_sign" },
    { c: "⛔", k: "no_entry" },
    { c: "📛", k: "name_badge" },
    { c: "🚫", k: "prohibited" },
    { c: "💯", k: "hundred_points" },
    { c: "💢", k: "anger_symbol" },
    { c: "♨️", k: "hot_springs" },
    { c: "🚷", k: "no_pedestrians" },
    { c: "🚯", k: "no_littering" },
    { c: "🚳", k: "no_bicycles" },
    { c: "🚱", k: "non_potable_water" },
    { c: "🔞", k: "no_one_under_eighteen" },
    { c: "📵", k: "no_mobile_phones" },
    { c: "🚭", k: "no_smoking" },
    { c: "❗", k: "exclamation_mark" },
    { c: "❕", k: "white_exclamation_mark" },
    { c: "❓", k: "question_mark" },
    { c: "❔", k: "white_question_mark" },
    { c: "‼️", k: "double_exclamation_mark" },
    { c: "⁉️", k: "exclamation_question_mark" },
    { c: "🔅", k: "dim_button" },
    { c: "🔆", k: "bright_button" },
    { c: "〽️", k: "part_alternation_mark" },
    { c: "⚠️", k: "warning" },
    { c: "🚸", k: "children_crossing" },
    { c: "🔱", k: "trident_emblem" },
    { c: "⚜️", k: "fleur_de_lis" },
    { c: "🔰", k: "japanese_symbol_beginner" },
    { c: "♻️", k: "recycling_symbol" },
    { c: "✅", k: "check_mark_button" },
    { c: "🈯", k: "japanese_reserved_button" },
    { c: "💹", k: "chart_increasing_yen" },
    { c: "❇️", k: "sparkle" },
    { c: "✳️", k: "eight_spoked_asterisk" },
    { c: "❎", k: "cross_mark_button" },
    { c: "🌐", k: "globe_meridians" },
    { c: "💠", k: "diamond_dot" },
    { c: "Ⓜ️", k: "circled_m" },
    { c: "🌀", k: "cyclone" },
    { c: "💤", k: "zzz" },
    { c: "🏧", k: "atm_sign" },
    { c: "🚾", k: "water_closet" },
    { c: "♿", k: "wheelchair_symbol" },
    { c: "🅿️", k: "p_button" },
    { c: "🈳", k: "japanese_vacancy_button" },
    { c: "🈂️", k: "japanese_service_charge_button" },
    { c: "🛂", k: "passport_control" },
    { c: "🛃", k: "customs" },
    { c: "🛄", k: "baggage_claim" },
    { c: "🛅", k: "left_luggage" },
    { c: "🚹", k: "mens_room" },
    { c: "🚺", k: "womens_room" },
    { c: "🚼", k: "baby_symbol" },
    { c: "🚻", k: "restroom" },
    { c: "🚮", k: "litter_bin_sign" },
    { c: "🎦", k: "cinema" },
    { c: "📶", k: "antenna_bars" },
    { c: "🈁", k: "japanese_here_button" },
    { c: "🔣", k: "input_symbols" },
    { c: "ℹ️", k: "information" },
    { c: "🔤", k: "input_latin_letters" },
    { c: "🔡", k: "input_latin_lowercase" },
    { c: "🔠", k: "input_latin_uppercase" },
    { c: "🆖", k: "ng_button" },
    { c: "🆗", k: "ok_button" },
    { c: "🆙", k: "up_button" },
    { c: "🆒", k: "cool_button" },
    { c: "🆕", k: "new_button" },
    { c: "🆓", k: "free_button" },
    { c: "0️⃣", k: "keycap_0" },
    { c: "1️⃣", k: "keycap_1" },
    { c: "2️⃣", k: "keycap_2" },
    { c: "3️⃣", k: "keycap_3" },
    { c: "4️⃣", k: "keycap_4" },
    { c: "5️⃣", k: "keycap_5" },
    { c: "6️⃣", k: "keycap_6" },
    { c: "7️⃣", k: "keycap_7" },
    { c: "8️⃣", k: "keycap_8" },
    { c: "9️⃣", k: "keycap_9" },
    { c: "🔟", k: "keycap_10" },
    { c: "🔢", k: "input_numbers" },
    { c: "#️⃣", k: "keycap_hash" },
    { c: "*️⃣", k: "keycap_asterisk" },
    { c: "⏏️", k: "eject_button" },
    { c: "▶️", k: "play_button" },
    { c: "⏸️", k: "pause_button" },
    { c: "⏯️", k: "play_pause_button" },
    { c: "⏹️", k: "stop_button" },
    { c: "⏺️", k: "record_button" },
    { c: "⏭️", k: "next_track_button" },
    { c: "⏮️", k: "last_track_button" },
    { c: "⏩", k: "fast_forward_button" },
    { c: "⏪", k: "fast_reverse_button" },
    { c: "⏫", k: "fast_up_button" },
    { c: "⏬", k: "fast_down_button" },
    { c: "◀️", k: "reverse_button" },
    { c: "🔼", k: "upwards_button" },
    { c: "🔽", k: "downwards_button" },
    { c: "➡️", k: "right_arrow" },
    { c: "⬅️", k: "left_arrow" },
    { c: "⬆️", k: "up_arrow" },
    { c: "⬇️", k: "down_arrow" },
    { c: "↗️", k: "up_right_arrow" },
    { c: "↘️", k: "down_right_arrow" },
    { c: "↙️", k: "down_left_arrow" },
    { c: "↖️", k: "up_left_arrow" },
    { c: "↕️", k: "up_down_arrow" },
    { c: "↔️", k: "left_right_arrow" },
    { c: "↪️", k: "left_arrow_curving_right" },
    { c: "↩️", k: "right_arrow_curving_left" },
    { c: "⤴️", k: "right_arrow_curving_up" },
    { c: "⤵️", k: "right_arrow_curving_down" },
    { c: "🔀", k: "shuffle_tracks_button" },
    { c: "🔁", k: "repeat_button" },
    { c: "🔂", k: "repeat_single_button" },
    { c: "🔄", k: "counterclockwise_arrows_button" },
    { c: "🔃", k: "clockwise_vertical_arrows" },
    { c: "🎵", k: "musical_note" },
    { c: "🎶", k: "musical_notes" },
    { c: "➕", k: "plus" },
    { c: "➖", k: "minus" },
    { c: "➗", k: "divide" },
    { c: "✖️", k: "multiply" },
    { c: "♾️", k: "infinity" },
    { c: "💲", k: "heavy_dollar_sign" },
    { c: "💱", k: "currency_exchange" },
    { c: "™️", k: "trade_mark" },
    { c: "©️", k: "copyright" },
    { c: "®️", k: "registered" },
    { c: "〰️", k: "wavy_dash" },
    { c: "➰", k: "curly_loop" },
    { c: "➿", k: "double_curly_loop" },
    { c: "🔚", k: "end_arrow" },
    { c: "🔙", k: "back_arrow" },
    { c: "🔛", k: "on_arrow" },
    { c: "🔝", k: "top_arrow" },
    { c: "🔜", k: "soon_arrow" },
    { c: "✔️", k: "check_mark" },
    { c: "☑️", k: "check_box_check" },
    { c: "🔘", k: "radio_button" },
    { c: "🔴", k: "red_circle" },
    { c: "🟠", k: "orange_circle" },
    { c: "🟡", k: "yellow_circle" },
    { c: "🟢", k: "green_circle" },
    { c: "🔵", k: "blue_circle" },
    { c: "🟣", k: "purple_circle" },
    { c: "⚫", k: "black_circle" },
    { c: "⚪", k: "white_circle" },
    { c: "🟤", k: "brown_circle" },
    { c: "🔺", k: "red_triangle_pointed_up" },
    { c: "🔻", k: "red_triangle_pointed_down" },
    { c: "🔸", k: "small_orange_diamond" },
    { c: "🔹", k: "small_blue_diamond" },
    { c: "🔶", k: "large_orange_diamond" },
    { c: "🔷", k: "large_blue_diamond" },
    { c: "🔳", k: "white_square_button" },
    { c: "🔲", k: "black_square_button" },
    { c: "▪️", k: "black_small_square" },
    { c: "▫️", k: "white_small_square" },
    { c: "◾", k: "black_medium_small_square" },
    { c: "◽", k: "white_medium_small_square" },
    { c: "◼️", k: "black_medium_square" },
    { c: "◻️", k: "white_medium_square" },
    { c: "🟥", k: "red_square" },
    { c: "🟧", k: "orange_square" },
    { c: "🟨", k: "yellow_square" },
    { c: "🟩", k: "green_square" },
    { c: "🟦", k: "blue_square" },
    { c: "🟪", k: "purple_square" },
    { c: "⬛", k: "black_large_square" },
    { c: "⬜", k: "white_large_square" },
    { c: "🟫", k: "brown_square" },
    { c: "🔈", k: "speaker_low_volume" },
    { c: "🔇", k: "muted_speaker" },
    { c: "🔉", k: "speaker_medium_volume" },
    { c: "🔊", k: "speaker_high_volume" },
    { c: "🔔", k: "bell" },
    { c: "🔕", k: "bell_slash" },
    { c: "📣", k: "megaphone" },
    { c: "📢", k: "loudspeaker" },
    { c: "👁‍🗨", k: "eye_speech_bubble" },
    { c: "💬", k: "speech_balloon" },
    { c: "💭", k: "thought_balloon" },
    { c: "🗯️", k: "right_anger_bubble" },
    { c: "♠️", k: "spade_suit" },
    { c: "♣️", k: "club_suit" },
    { c: "♥️", k: "heart_suit" },
    { c: "♦️", k: "diamond_suit" },
    { c: "🃏", k: "joker" },
    { c: "🎴", k: "flower_playing_cards" },
    { c: "🀄", k: "mahjong_red_dragon" },
    { c: "🕐", k: "one_o_clock" },
    { c: "🕑", k: "two_o_clock" },
    { c: "🕒", k: "three_o_clock" },
    { c: "🕓", k: "four_o_clock" },
    { c: "🕔", k: "five_o_clock" },
    { c: "🕕", k: "six_o_clock" },
    { c: "🕖", k: "seven_o_clock" },
    { c: "🕗", k: "eight_o_clock" },
    { c: "🕘", k: "nine_o_clock" },
    { c: "🕙", k: "ten_o_clock" },
    { c: "🕚", k: "eleven_o_clock" },
    { c: "🕛", k: "twelve_o_clock" },
  ],
  flags: [
    { c: "🏁", k: "chequered_flag" },
    { c: "🚩", k: "triangular_flag" },
    { c: "🎌", k: "crossed_flags" },
    { c: "🏴", k: "black_flag" },
    { c: "🏳️", k: "white_flag" },
    { c: "🏳️‍🌈", k: "rainbow_flag" },
    { c: "🏳️‍⚧️", k: "transgender_flag" },
    { c: "🏴‍☠️", k: "pirate_flag" },
    { c: "🇦🇫", k: "flag_afghanistan" },
    { c: "🇦🇽", k: "flag_aland_islands" },
    { c: "🇦🇱", k: "flag_albania" },
    { c: "🇩🇿", k: "flag_algeria" },
    { c: "🇦🇸", k: "flag_american_samoa" },
    { c: "🇦🇩", k: "flag_andorra" },
    { c: "🇦🇴", k: "flag_angola" },
    { c: "🇦🇮", k: "flag_anguilla" },
    { c: "🇦🇶", k: "flag_antarctica" },
    { c: "🇦🇬", k: "flag_antigua_barbuda" },
    { c: "🇦🇷", k: "flag_argentina" },
    { c: "🇦🇲", k: "flag_armenia" },
    { c: "🇦🇼", k: "flag_aruba" },
    { c: "🇦🇺", k: "flag_australia" },
    { c: "🇦🇹", k: "flag_austria" },
    { c: "🇦🇿", k: "flag_azerbaijan" },
    { c: "🇧🇸", k: "flag_bahamas" },
    { c: "🇧🇭", k: "flag_bahrain" },
    { c: "🇧🇩", k: "flag_bangladesh" },
    { c: "🇧🇧", k: "flag_barbados" },
    { c: "🇧🇾", k: "flag_belarus" },
    { c: "🇧🇪", k: "flag_belgium" },
    { c: "🇧🇿", k: "flag_belize" },
    { c: "🇧🇯", k: "flag_benin" },
    { c: "🇧🇲", k: "flag_bermuda" },
    { c: "🇧🇹", k: "flag_bhutan" },
    { c: "🇧🇴", k: "flag_bolivia" },
    { c: "🇧🇦", k: "flag_bosnia_herzegovina" },
    { c: "🇧🇼", k: "flag_botswana" },
    { c: "🇧🇷", k: "flag_brazil" },
    { c: "🇮🇴", k: "flag_british_indian_ocean_territory" },
    { c: "🇻🇬", k: "flag_british_virgin_islands" },
    { c: "🇧🇳", k: "flag_brunei" },
    { c: "🇧🇬", k: "flag_bulgaria" },
    { c: "🇧🇫", k: "flag_burkina_faso" },
    { c: "🇧🇮", k: "flag_burundi" },
    { c: "🇰🇭", k: "flag_cambodia" },
    { c: "🇨🇲", k: "flag_cameroon" },
    { c: "🇨🇦", k: "flag_canada" },
    { c: "🇮🇨", k: "flag_canary_islands" },
    { c: "🇨🇻", k: "flag_cape_verde" },
    { c: "🇧🇶", k: "flag_caribbean_netherlands" },
    { c: "🇰🇾", k: "flag_cayman_islands" },
    { c: "🇨🇫", k: "flag_central_african_republic" },
    { c: "🇹🇩", k: "flag_chad" },
    { c: "🇨🇱", k: "flag_chile" },
    { c: "🇨🇳", k: "flag_china" },
    { c: "🇨🇽", k: "flag_christmas_island" },
    { c: "🇨🇨", k: "flag_cocos_keeling_islands" },
    { c: "🇨🇴", k: "flag_colombia" },
    { c: "🇰🇲", k: "flag_comoros" },
    { c: "🇨🇬", k: "flag_congo_brazzaville" },
    { c: "🇨🇩", k: "flag_congo_kinshasa" },
    { c: "🇨🇰", k: "flag_cook_islands" },
    { c: "🇨🇷", k: "flag_costa_rica" },
    { c: "🇨🇮", k: "flag_cote_divoire" },
    { c: "🇭🇷", k: "flag_croatia" },
    { c: "🇨🇺", k: "flag_cuba" },
    { c: "🇨🇼", k: "flag_curacao" },
    { c: "🇨🇾", k: "flag_cyprus" },
    { c: "🇨🇿", k: "flag_czechia" },
    { c: "🇩🇰", k: "flag_denmark" },
    { c: "🇩🇯", k: "flag_djibouti" },
    { c: "🇩🇲", k: "flag_dominica" },
  ],
};

// Skin tone modifiers - null represents default (no skin tone)
export const skinTones = [null, "🏻", "🏼", "🏽", "🏾", "🏿"];

// Skin tone color mapping
export const skinToneColors: Record<string, string> = {
  null: "#ffcc22", // Yellow for default
  "🏻": "#ffdbb4",
  "🏼": "#eac086",
  "🏽": "#d4965f",
  "🏾": "#a37854",
  "🏿": "#6e4a3a",
  default: "#ffcc22",
};

// Category icons mapping (using keys)
export const categoryIcons: Record<CategoryKey, string> = {
  smileys_people: "😀",
  animals_nature: "🐶",
  food_drink: "🍕",
  activity: "⚽",
  travel_places: "✈️",
  objects: "💡",
  symbols: "❤️",
  flags: "🏁",
};

// List of base emojis that support skin tones
export const skinToneEmojis = new Set([
  "👋",
  "🤚",
  "🖐",
  "✋",
  "🖖",
  "👌",
  "🤌",
  "🤏",
  "✌",
  "🤞",
  "🤟",
  "🤘",
  "🤙",
  "👈",
  "👉",
  "👆",
  "🖕",
  "👇",
  "☝",
  "👍",
  "👎",
  "✊",
  "👊",
  "🤛",
  "🤜",
  "👏",
  "🙌",
  "👐",
  "🤲",
  "🤝",
  "🙏",
  "✍",
  "💅",
  "🤳",
  "💪",
  "🦵",
  "🦶",
  "👂",
  "🦻",
  "👃",
  "👶",
  "👧",
  "🧒",
  "👦",
  "👩",
  "🧑",
  "👨",
  "👩‍🦱",
  "🧑‍🦱",
  "👨‍🦱",
  "👩‍🦰",
  "🧑‍🦰",
  "👨‍🦰",
  "👱‍♀️",
  "👱",
  "👱‍♂️",
  "👩‍🦳",
  "🧑‍🦳",
  "👨‍🦳",
  "👩‍🦲",
  "🧑‍🦲",
  "👨‍🦲",
  "🧔‍♀️",
  "🧔",
  "🧔‍♂️",
  "👵",
  "🧓",
  "👴",
  "👲",
  "👳‍♀️",
  "👳",
  "👳‍♂️",
  "🧕",
  "👮‍♀️",
  "👮",
  "👮‍♂️",
  "👷‍♀️",
  "👷",
  "👷‍♂️",
  "💂‍♀️",
  "💂",
  "💂‍♂️",
  "🕵‍♀️",
  "🕵",
  "🕵‍♂️",
  "👩‍⚕️",
  "🧑‍⚕️",
  "👨‍⚕️",
  "👩‍🌾",
  "🧑‍🌾",
  "👨‍🌾",
  "👩‍🍳",
  "🧑‍🍳",
  "👨‍🍳",
  "👩‍🎓",
  "🧑‍🎓",
  "👨‍🎓",
  "👩‍🎤",
  "🧑‍🎤",
  "👨‍🎤",
  "👩‍🏫",
  "🧑‍🏫",
  "👨‍🏫",
  "👩‍🏭",
  "🧑‍🏭",
  "👨‍🏭",
  "👩‍💻",
  "🧑‍💻",
  "👨‍💻",
  "👩‍💼",
  "🧑‍💼",
  "👨‍💼",
  "👩‍🔧",
  "🧑‍🔧",
  "👨‍🔧",
  "👩‍🔬",
  "🧑‍🔬",
  "👨‍🔬",
  "👩‍🎨",
  "🧑‍🎨",
  "👨‍🎨",
  "👩‍🚒",
  "🧑‍🚒",
  "👨‍🚒",
  "👩‍✈️",
  "🧑‍✈️",
  "👨‍✈️",
  "👩‍🚀",
  "🧑‍🚀",
  "👨‍🚀",
  "👩‍⚖️",
  "🧑‍⚖️",
  "👨‍⚖️",
  "👰‍♀️",
  "👰",
  "👰‍♂️",
  "🤵‍♀️",
  "🤵",
  "🤵‍♂️",
  "👸",
  "🤴",
  "🥷",
  "🦸‍♀️",
  "🦸",
  "🦸‍♂️",
  "🦹‍♀️",
  "🦹",
  "🦹‍♂️",
  "🧙‍♀️",
  "🧙",
  "🧙‍♂️",
  "🧚‍♀️",
  "🧚",
  "🧚‍♂️",
  "🧛‍♀️",
  "🧛",
  "🧛‍♂️",
  "🧜‍♀️",
  "🧜",
  "🧜‍♂️",
  "🧝‍♀️",
  "🧝",
  "🧝‍♂️",
  "🧞‍♀️",
  "🧞",
  "🧞‍♂️",
  "🧟‍♀️",
  "🧟",
  "🧟‍♂️",
  "💆‍♀️",
  "💆",
  "💆‍♂️",
  "💇‍♀️",
  "💇",
  "💇‍♂️",
  "🚶‍♀️",
  "🚶",
  "🚶‍♂️",
  "🧍‍♀️",
  "🧍",
  "🧍‍♂️",
  "🧎‍♀️",
  "🧎",
  "🧎‍♂️",
  "🧑‍🦯",
  "👨‍🦯",
  "👩‍🦯",
  "🧑‍🦼",
  "👨‍🦼",
  "👩‍🦼",
  "🧑‍🦽",
  "👨‍🦽",
  "👩‍🦽",
  "🏃‍♀️",
  "🏃",
  "🏃‍♂️",
  "💃",
  "🕺",
  "🕴",
  "👯‍♀️",
  "👯",
  "👯‍♂️",
  "🧖‍♀️",
  "🧖",
  "🧖‍♂️",
  "🧗‍♀️",
  "🧗",
  "🧗‍♂️",
  "🏇",
  "🏂",
  "🏌‍♀️",
  "🏌",
  "🏌‍♂️",
  "🏄‍♀️",
  "🏄",
  "🏄‍♂️",
  "🚣‍♀️",
  "🚣",
  "🚣‍♂️",
  "🏊‍♀️",
  "🏊",
  "🏊‍♂️",
  "⛹‍♀️",
  "⛹",
  "⛹‍♂️",
  "🏋‍♀️",
  "🏋",
  "🏋‍♂️",
  "🚴‍♀️",
  "🚴",
  "🚴‍♂️",
  "🚵‍♀️",
  "🚵",
  "🚵‍♂️",
  "🤸‍♀️",
  "🤸",
  "🤸‍♂️",
  "🤼‍♀️",
  "🤼‍♂️",
  "🤽‍♀️",
  "🤽",
  "🤽‍♂️",
  "🤾‍♀️",
  "🤾",
  "🤾‍♂️",
  "🤹‍♀️",
  "🤹",
  "🤹‍♂️",
  "🧘‍♀️",
  "🧘",
  "🧘‍♂️",
  "🛀",
  "🛌",
  "🧑‍🤝‍🧑",
  "👭",
  "👫",
  "👬",
  "💏",
  "💑",
  "👪",
  "🤱",
  "🤰",
  "🫃",
  "🫄",
  "👼",
]);
